# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 18:35
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Border',
            fields=[
                ('country_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('border_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('city', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=api.models.get_upload_path)),
            ],
        ),
    ]
